[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "solmate/=lib/v4-core/lib/solmate/",
]

evm_version = "cancun"
solc_version = "0.8.26"

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
